version: '2'

yml-anchors:  # defines some yml anchors so that we DRY
   sharedvol: &sharedvol
     volumes:
       - "./codeship-distfiles:/opt/distfiles"

   testenv: &testenv
      add_docker: true
      working_dir: /opt/test
      volumes:
       - "./codeship-distfiles:/opt/distfiles"

   testbuild: &testbuild
      context: .
      dockerfile: deployment/Dockerfile.testenv


services:
  avirshup/docker-make:  # this is the deployment artifact
    <<: *sharedvol
    build:
      dockerfile: Dockerfile
      context: .

  testenv-python3.6:
    <<: *testenv
    build:
      <<: *testbuild
      args:
        PYVERSION: "3.6"

  testenv-python3.7:
    <<: *testenv
    build:
      <<: *testbuild
      args:
        PYVERSION: "3.7"

  testenv-python3.8:
    <<: *testenv
    build:
      <<: *testbuild
      args:
        PYVERSION: "3.8"

  deploy-env:
    <<: *sharedvol
    add_docker: true
    build:
      context: deployment/
      dockerfile: Dockerfile.deploy
    encrypted_env_file: deployment/tokens.crypt

